services:
  app:
    build: .
    container_name: firebird-viewer-app
    ports:
      - "8080:8080"
    #depends_on:
    #  - firebird
    #networks:
    #  - firebird-net

  #firebird:
  #  image: firebird:3.0
  #  container_name: firebird-db
  #  environment:
  #    - ISC_PASSWORD=masterkey
  #  ports:
  #    - "3050:3050"
  #  volumes:
  #    - firebird_data:/firebird/data
  #  networks:
  #    - firebird-net

volumes:
  firebird_data:

networks:
  firebird-net:
    driver: bridge
